apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: {{ .Release.Namespace }}
  {{- if .Values.service.certificateArn }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.service.certificateArn }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: mcp-server
  ports:
    {{- if .Values.service.certificateArn }}
    - name: https
      port: 443
      targetPort: {{ .Values.service.port }}
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    {{- end }}
